### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by Acadbek** [aksharahegde/nuxt-glow#1]
![Capture](https://github.com/aksharahegde/nuxt-glow/assets/87940040/6eeff367-368a-469e-b470-645ffae0d1e2)

**Comment by aksharahegde** [comment]
it works only with nuxt with tailwindcss projects and can you try copying this whole component from [Playground Component](https://github.com/aksharahegde/nuxt-glow/blob/main/playground/app.vue). 
If its not working, then check if the below code has been added to `tailwind.config.js`
```js
plugins: [
    require('@aksharahegde/nuxt-glow/tailwind')
  ]```

**Comment by Acadbek** [comment]
> it works only with nuxt with tailwindcss projects and can you try copying this whole component from [Playground Component](https://github.com/aksharahegde/nuxt-glow/blob/main/playground/app.vue). If its not working, then check if the below code has been added to `tailwind.config.js`
> 
> ```js
> plugins: [
>     require('@aksharahegde/nuxt-glow/tailwind')
>   ]
> ```

my project have nuxt and unocss
